# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-17 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', models.CharField(max_length=6, unique=True, verbose_name='股票代码')),
                ('stock_name', models.CharField(max_length=32, verbose_name='股票简称')),
                ('stock_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='股票现价(元)')),
                ('stock_increase', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='股票涨幅(%)')),
                ('stock_concept', models.CharField(max_length=1024, verbose_name='概念解析')),
                ('stock_concept_num', models.IntegerField(max_length=5, verbose_name='所属概念数量')),
                ('stock_market_value', models.CharField(max_length=16, verbose_name='市值(亿)')),
                ('stock_industry', models.CharField(max_length=32, verbose_name='所属行业')),
            ],
            options={
                'db_table': 'stock',
            },
        ),
    ]
