# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-17 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(max_length=11, unique=True, verbose_name='用户Id')),
                ('name', models.CharField(max_length=11, verbose_name='姓名')),
                ('id_card', models.CharField(max_length=18, unique=True, verbose_name='身份证号')),
                ('bank_id', models.IntegerField(max_length=3, verbose_name='所属银行')),
                ('bank_no', models.IntegerField(max_length=19, verbose_name='银行卡号')),
                ('addr', models.CharField(default='', max_length=1024, verbose_name='居住地址')),
                ('is_opened', models.IntegerField(default=0, max_length=1, verbose_name='是否开户')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'account',
            },
        ),
    ]
