# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-17 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='bank_no',
            field=models.IntegerField(max_length=20, verbose_name='银行卡号'),
        ),
    ]
