# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-17 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='funds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funds_id', models.CharField(max_length=6, unique=True, verbose_name='基金代码')),
                ('funds_name', models.CharField(max_length=32, verbose_name='基金简称')),
                ('funds_accu', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='累计净值')),
                ('funds_day_val', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='日增长值')),
                ('funds_day_rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='日增长率')),
                ('funds_year_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='申购状态')),
            ],
            options={
                'db_table': 'funds',
            },
        ),
    ]
