# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-17 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='tag',
            field=models.CharField(max_length=11, verbose_name='标签'),
        ),
    ]
