# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-17 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200117_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='bank_no',
            field=models.IntegerField(max_length=19, verbose_name='银行卡号'),
        ),
    ]
