# Generated by Django 2.1.1 on 2020-01-23 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200117_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.AlterField(
            model_name='weibouser',
            name='uid',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.UserProfile'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
