# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-17 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(max_length=11, verbose_name='用户Id')),
                ('fian_code', models.CharField(max_length=1042, verbose_name='股票或基金的代码')),
                ('fian_price', models.IntegerField(max_length=11, verbose_name='订单支付的钱')),
                ('order_status', models.IntegerField(max_length=1, verbose_name='订单的状态')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
