# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-18 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fian_type',
            field=models.IntegerField(default=0, max_length=1, verbose_name='基金或股票的类型'),
        ),
    ]
