# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-18 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_fian_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fian_price',
            field=models.FloatField(max_length=11, verbose_name='订单支付的钱'),
        ),
    ]
